// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementService.Data;

#nullable disable

namespace ProductManagementService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240226190438_SeedGroupsWithSubgroups")]
    partial class SeedGroupsWithSubgroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagementService.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Antigua And Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Bosnia And Herzegowina"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 32,
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 45,
                            Name = "China"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Cote D'Ivoire"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Croatia (Local Name: Hrvatska)"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 62,
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 65,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 74,
                            Name = "France"
                        },
                        new
                        {
                            Id = 75,
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 76,
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 77,
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Icel And"
                        },
                        new
                        {
                            Id = 98,
                            Name = "India"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Iran (Islamic Republic Of)"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Lao People'S Dem Republic"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Macau"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Micronesia, Federated States"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Moldova, Republic Of"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Netherlands Ant Illes"
                        },
                        new
                        {
                            Id = 150,
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 151,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Saint K Itts And Nevis"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Saint Vincent, The Grenadines"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 180,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Sao Tome And Principe"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Slovakia (Slovak Republic)"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 191,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 192,
                            Name = "South Georgia , S Sandwich Is."
                        },
                        new
                        {
                            Id = 193,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 195,
                            Name = "St. Helena"
                        },
                        new
                        {
                            Id = 196,
                            Name = "St. Pierre And Miquelon"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Svalbard, Jan Mayen Islands"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Sw Aziland"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Tanzania, United Republic Of"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Trinidad And Tobago"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Turks And Caicos Islands"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 219,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 220,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 221,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 222,
                            Name = "United States Minor Is."
                        },
                        new
                        {
                            Id = 223,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Virgin Islands (British)"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Virgin Islands (U.S.)"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Wallis And Futuna Islands"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Yugoslavia"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Zaire"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("ProductManagementService.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "პროდუქტები"
                        },
                        new
                        {
                            Id = 3,
                            Name = "აგრარული",
                            ParentGroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "კვება",
                            ParentGroupId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "ხილი",
                            ParentGroupId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "ბოსტნეული",
                            ParentGroupId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "სასმელები",
                            ParentGroupId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "კერძები",
                            ParentGroupId = 4
                        });
                });

            modelBuilder.Entity("ProductManagementService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("GroupId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "001",
                            CountryId = 80,
                            EndDate = new DateTime(2024, 3, 27, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4436),
                            GroupId = 3,
                            Name = "ვაშლი",
                            Price = 2.9900000000000002,
                            StartDate = new DateTime(2024, 2, 26, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4424)
                        },
                        new
                        {
                            Id = 2,
                            Code = "002",
                            CountryId = 213,
                            EndDate = new DateTime(2024, 2, 28, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4445),
                            GroupId = 3,
                            Name = "მსხალი",
                            Price = 3.9900000000000002,
                            StartDate = new DateTime(2024, 2, 11, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4445)
                        },
                        new
                        {
                            Id = 3,
                            Code = "003",
                            CountryId = 16,
                            EndDate = new DateTime(2024, 3, 3, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4448),
                            GroupId = 3,
                            Name = "საზამთრო",
                            Price = 5.5,
                            StartDate = new DateTime(2024, 2, 23, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4447)
                        },
                        new
                        {
                            Id = 4,
                            Code = "004",
                            CountryId = 80,
                            EndDate = new DateTime(2024, 3, 4, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4450),
                            GroupId = 7,
                            Name = "კოკა-კოლა",
                            Price = 4.2000000000000002,
                            StartDate = new DateTime(2024, 2, 20, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4449)
                        },
                        new
                        {
                            Id = 5,
                            Code = "005",
                            CountryId = 80,
                            EndDate = new DateTime(2024, 2, 29, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4452),
                            GroupId = 7,
                            Name = "პეპსი",
                            Price = 4.0,
                            StartDate = new DateTime(2024, 2, 25, 23, 4, 36, 572, DateTimeKind.Local).AddTicks(4451)
                        });
                });

            modelBuilder.Entity("ProductManagementService.Models.Group", b =>
                {
                    b.HasOne("ProductManagementService.Models.Group", "ParentGroup")
                        .WithMany("Subgroups")
                        .HasForeignKey("ParentGroupId");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("ProductManagementService.Models.Product", b =>
                {
                    b.HasOne("ProductManagementService.Models.Country", "Country")
                        .WithMany("Products")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductManagementService.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ProductManagementService.Models.Country", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductManagementService.Models.Group", b =>
                {
                    b.Navigation("Subgroups");
                });
#pragma warning restore 612, 618
        }
    }
}
